    public enum TouhouCrisisSounds {
        PlayerHurt,
        Reload,
        Handgun_Fire,
        Handgun_Dryfire,
        EnemySword,
        DeflectLast,
        PuckChange,
        ReloadVO,
        ActionVO,
        WaitBeep,
        KnifePlace,
        SpellcardBreak,
        TimeStop,
        TimeResumes,
        BulletCasings,
        MenuButton,
        EnemyDeath,
        UFOBullet,
        PlayerHurtRemote,
        PlayerJoin,
        ScoreBeeps
    }
    public enum TouhouCrisisMusic {
        FloweringNight,
        LunaDial,
        LunaDialLowPass,
        GameOverLose,
        GameOverWin
    }
